name: Check inactive
# Check inactive issues and label `inactive` if it is inactive for 30 days
# 10일 동안 활동이 없는 이슈를 찾아서 inactive 라벨을 붙임

on:
  schedule:
    - cron: "0 0 1 * *"
# 매일 1일마다 실행

jobs:
  check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-inactive'
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 10
