name: Deploy Docs

on:
  push:
    branches: [ "3.0" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Cache node module
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Docs
        run: npm run docs_build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          publish_dir: ./dist

      - name: Send jandi when failed
        if: ${{ failure() }}
        uses: ./.github/actions/jandi-notify
        with:
          jandi_incoming_url: ${{ secrets.JANDI_INCOMING_URL }}

      - name: Send jandi if completed
        if: ${{ success() }}
        uses: ./.github/actions/jandi-notify
        with:
          status: success
          jandi_incoming_url: ${{ secrets.JANDI_INCOMING_URL }}
